### ISSUE TITLE
Change the language in the banner area

### ISSUE THREAD

**Issue by jwinterm** [sammy007/aeon-site#1]
Specifically these three lines:   
```
<h1><strong>AEON</strong> isn't a cryptocurrency.<br/><strong>It's a lifestyle.</strong></h1>
            <p class="lead"><strong>It's about polished perfection, attained by breaking the rules with calculated mastery of the art.<strong></p>
            <p class="lead">It's about respecting history and pushing innovation forward at the same time. It's about more than just math: it's a vision of a world where luxury is the same as entry-level, and the limits are the heavens themselves. <small>&copy; americanpegasus</small></p>
```  
There was some discussion on bitcointalk that this rhetoric is a bit over the top, and makes people think of timeshares or something, with even the quote's originator [suggesting it should be changed](https://bitcointalk.org/index.php?topic=1197508.msg17945817#msg17945817).  

I don't have anything in particular in mind, just opening an issue so people can put their thoughts down in a more focused thread for discussion.

**Comment by sammy007** [comment]
Need a PR.
